printWidth = 80
tabWidth = 4,
useTabs = false
semi = true
singleQuote = true
quoteProps = "as-needed"
trailingComma = "all"
bracketSpacing = true
objectWrap = "preserve"
bracketSameLine = true
arrowParens = "always"
insertPragma = false
proseWrap = "preserve"
htmlWhitespaceSensitivity = "css"
